#!/usr/bin/env bash
set -euo pipefail

# altfins_signals.sh — Get trading signals feed from altFINS
#
# Fetches 130+ trading signals (bullish/bearish) generated by the altFINS platform.
# Signals include: MA crossovers, RSI divergences, chart patterns, candlestick
# patterns, trend changes, support/resistance, and more.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_lib.sh"

usage() {
  show_help "altfins_signals.sh" \
    "Get trading signals feed — MA crossovers, patterns, momentum, etc." \
    "altfins_signals.sh [options]" \
    "Options:
  --symbols <json>        JSON array of symbols, e.g. '[\"BTC\",\"ETH\"]' (default: all)
  --signals <json>        JSON array of signal keys to filter (default: all)
  --direction <dir>       BULLISH or BEARISH (default: both)
  --from <iso-date>       Start date in ISO 8601 format
  --to <iso-date>         End date in ISO 8601 format
  --days <n>              Shorthand: fetch last N days (default: 1)
  --page <n>              Page number (default: 0)
  --size <n>              Page size (default: 50)
  --all                   Fetch all pages
  --list-keys             List all available signal keys
  --help                  Show this help

Signal Categories (use --list-keys for full list):
  MA Crossovers:    EMA_12_50_CROSSOVERS, SIGNALS_SUMMARY_SMA_50_200, ...
  RSI:              SIGNALS_SUMMARY_RSI_14, SIGNALS_SUMMARY_RSI_DIVERGENCE, ...
  MACD:             FRESH_MOMENTUM_MACD_SIGNAL_LINE_CROSSOVER, ...
  Patterns:         SIGNALS_SUMMARY_DOUBLE_BOTTOM, SIGNALS_SUMMARY_HEAD_AND_SHOULDERS, ...
  Candlesticks:     SIGNALS_SUMMARY_HAMMER, SIGNALS_SUMMARY_ENGULFING, ...
  Trends:           UP_DOWN_TREND, SIGNALS_SUMMARY_STRONG_UP_DOWN_TREND, ...
  Support/Resist:   SUPPORT_RESISTANCE_BREAKOUT, SUPPORT_RESISTANCE_APPROACHING, ...
  Gainers/Losers:   SIGNALS_SUMMARY_TOP_GAINERS, SIGNALS_SUMMARY_TOP_LOSERS, ..."
}

# Defaults
symbols="[]"
signals="[]"
direction=""
from_date=""
to_date=""
days=1
page=0
size=50
fetch_all=false
list_keys=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --symbols)    symbols="$2"; shift 2 ;;
    --signals)    signals="$2"; shift 2 ;;
    --direction)  direction="$2"; shift 2 ;;
    --from)       from_date="$2"; shift 2 ;;
    --to)         to_date="$2"; shift 2 ;;
    --days)       days="$2"; shift 2 ;;
    --page)       page="$2"; shift 2 ;;
    --size)       size="$2"; shift 2 ;;
    --all)        fetch_all=true; shift ;;
    --list-keys)  list_keys=true; shift ;;
    --help)       usage ;;
    *)
      echo "Error: unknown option '$1'" >&2
      exit 1 ;;
  esac
done

# List available signal keys
if [[ "$list_keys" == true ]]; then
  make_checked_request "GET" "/signals-feed/signal-keys" "list signal keys"
  exit $?
fi

if [[ -n "$direction" ]]; then
  validate_signal_direction "$direction"
fi

# Default date range
if [[ -z "$from_date" ]]; then
  from_date=$(iso_date "$days")
fi
if [[ -z "$to_date" ]]; then
  to_date=$(iso_date 0)
fi

payload=$(jq -n \
  --argjson symbols "$symbols" \
  --argjson signals "$signals" \
  --arg from "$from_date" \
  --arg to "$to_date" \
  '{symbols: $symbols, signals: $signals, fromDate: $from, toDate: $to}')

# Add optional direction
if [[ -n "$direction" ]]; then
  payload=$(echo "$payload" | jq --arg dir "$direction" '. + {signalDirection: $dir}')
fi

if [[ "$fetch_all" == true ]]; then
  paginate_request "/signals-feed/search-requests" "$payload" "signals feed"
else
  make_checked_request "POST" "/signals-feed/search-requests?page=${page}&size=${size}" "signals feed" "$payload"
fi
